### ISSUE TITLE
Not working in MI phones even after auto start allow

### ISSUE THREAD

**Issue by ghost** [arvi/neverendingbackgroundservice#2]
please help me in that 

in mi phones not working in the background even I give auto start permission in MI 

please help me with that and give me a solution

**Comment by arvi** [comment]
@chiragmobibox Hello. I built this for work use 2 years ago and a lot may have changed in android since then. I think you can use this as base for similar purpose and modify or fix issues you're having. My work now doesn't involve any android development so I'm not really updated with it anymore.

Cheers.

**Comment by ghost** [comment]
> @chiragmobibox Hello. I built this for work use 2 years ago and a lot may have changed in android since then. I think you can use this as base for similar purpose and modify or fix issues you're having. My work now doesn't involve any android development so I'm not really updated with it anymore.
> 
> Cheers.

Hi Arvi,

that's ok but do you have new code link or anything else to understand background services

and yes this code is working with samsung phones perfectly 

so i need only help in MI,Vivo,Oppo

**Comment by arvi** [comment]
@chiragmobibox you can always do a quick search in stackoverflow since the nature of your issue is not isolated.

Maybe this would help: [https://stackoverflow.com/a/50291806/2098493](https://stackoverflow.com/a/50291806/2098493)

As for the source of my repo on never ending service, it's based on here:
[https://fabcirablog.weebly.com/blog/creating-a-never-ending-background-service-in-android](https://fabcirablog.weebly.com/blog/creating-a-never-ending-background-service-in-android)

**Comment by ghost** [comment]
> @chiragmobibox you can always do a quick search in stackoverflow since the nature of your issue is not isolated.
> 
> Maybe this would help: https://stackoverflow.com/a/50291806/2098493
> 
> As for the source of my repo on never ending service, it's based on here:
> https://fabcirablog.weebly.com/blog/creating-a-never-ending-background-service-in-android

Thanks
